---
language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

services:
  - xvfb                      # Fake X11

addons:
  apt:
    packages:
      - libxcb-shape0-dev     # Because we use X11
      - libxcb-xfixes0-dev    # Because we use X11

cache: cargo
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo clean
  - cargo build
  - cargo test
