[package]
name = "clipboard"
version = "0.0.3"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]

[dependencies]
libc = "*"

[target.i686-pc-windows-gnu.dependencies]
clipboard-win = "1.6.0"

[target.x86_64-pc-windows-gnu.dependencies]
clipboard-win = "1.6.0"

[target.i686-apple-darwin.dependencies]
objc = "0.1.6"
objc_id = "0.0.2"
objc-foundation = "0.0.2"

[target.x86_64-apple-darwin.dependencies]
objc = "0.1.6"
objc_id = "0.0.2"
objc-foundation = "0.0.2"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib", "xmu"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib", "xmu"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "2.0.0"
features = ["xlib", "xmu"]

[target.aarch64-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib", "xmu"]
