[package]

name = "clipboard"
version = "0.1.2"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
description = "rust-clipboard is a cross-platform library for getting and setting the contents of the OS-level clipboard."
repository = "https://github.com/aweinstock314/rust-clipboard"
license = "Apache-2.0/GPL-2.0"
keywords = ["clipboard"]

[target.'cfg(windows)'.dependencies]
clipboard-win = "1.5.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
objc_id = "0.1"
objc-foundation = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2.3.0", features = ["xlib", "xmu"] }
