[package]
name = "clipboard"
version = "0.5.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
description = "rust-clipboard is a cross-platform library for getting and setting the contents of the OS-level clipboard."
repository = "https://github.com/aweinstock314/rust-clipboard"
license = "MIT / Apache-2.0"
keywords = ["clipboard"]

[features]
default = ["macos", "windows", "x11"]

macos = ["objc", "objc_id", "objc-foundation"]
windows = ["clipboard-win"]
x11 = ["x11-clipboard"]

[target.'cfg(windows)'.dependencies]
clipboard-win = { version = "2.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "0.2", optional = true }
objc_id = { version = "0.1", optional = true }
objc-foundation = { version = "0.1", optional = true }

[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten"))))'.dependencies]
x11-clipboard = { version = "0.3", optional = true }
